package ch.ielse.demo.p05.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ch.ielse.demo.p05.db.PersonInfo;

import ch.ielse.demo.p05.db.PersonInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInfoDaoConfig;

    private final PersonInfoDao personInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);

        registerDao(PersonInfo.class, personInfoDao);
    }
    
    public void clear() {
        personInfoDaoConfig.clearIdentityScope();
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

}
